### ISSUE TITLE
Package tempest/console is not available on Packagist

### ISSUE THREAD

**Issue by PierreThiollent** [tempestphp/tempest-console#6]
I tried to install the tempest-console package running `composer require tempest/console` but I got this error message : 

> Could not find a matching version of package tempest/console. Check the package spelling, your version constraint and that the package is available in a stability which matches   
  your minimum-stability (stable).

When I search the package on Packagist I could not find it.

**Comment by brendt** [comment]
It is available but not tagged. You should `require tempest/console:dev-main`

This package is still very unstable, please don't use it yet except for experimentation :D
